### ISSUE TITLE
Issuベースの開発レビュー依頼

### ISSUE THREAD

**Issue by Yamanaka78** [Yamanaka78/HiddenGems-#39]
■Webアプリの概要

このサービスは、観光地口コミサービスです。あまり知られてない観光地などを個人が紹介したり、観光地の口コミ投稿とオリジナル旅行プランの作成・共有を通じて、ユーザー同士が観光情報を交換するプラットフォームです。ユーザーは自身が訪れた観光スポットを紹介し、他のユーザーがそのスポットに対する口コミや評価を投稿することができます。また、ユーザーは行きたいスポットをリストに追加し、自分だけのオリジナル旅行プランを作成・共有できます。旅行後には写真や動画をアップロードして、思い出をまとめたオリジナルアルバムを作成することができます。
■ProjectsのURL
https://github.com/users/Yamanaka78/projects/1/views/1

■MVPリリースまで
- [ ] 技術選定
- [ ] サーバー構築
- [ ] 環境構築
- [ ] アプリケーションの雛形作成
- [ ] トップページの作成
- [ ] ログインページ
- [ ] 新規登録ページ
- [ ] スポット検索結果ページの実装
- [ ] スポット一覧ページの実装
- [ ] スポット詳細ページの実装
- [ ] スポット登録ページ
- [ ] 口コミ一覧、詳細ページの実装
- [ ] 行きたいリストページの実装
- [ ] プラン作成ページの実装
- [ ] プラン詳細ページの実装
- [ ] おすすめプラン詳細
- [ ] おすすめプラン一覧ページの実装
- [ ] MVPリリース

■MVP後
- [ ] ユーザープロフィールページ
- [ ] オリジナルアルバム作成ページ
- [ ] アルバム一覧ページ
- [ ] アルバム共有ページ
- [ ] ログインページの拡張
- [ ] スポット検索ページの拡張
- [ ] スポット詳細ページの拡張
- [ ] プラン作成ページの拡張
- [ ] トップページの拡張
- [ ] パスワードリセット画面の実装
- [ ] パスワード再登録画面の実装
- [ ] SNSでの新規登録処理の作成
- [ ] コミュニティページの実装
- [ ] メールアドレス変更依頼
- [ ] メールアドレス変更画面
- [ ] 地図表示の作成
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ

■MVPレビュー依頼予定日
予定日：2024年 10月 26日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- アルバム
- ユーザープロフィール
